mic_cms_ms_api:
  build: web/
  tty: true
  ports:
    - "8077:80"
  volumes:
    - ../:/var/www/html
  links:
    - mic_cms_ms_mongo:mongo
  environment:
    ENVIRONMENT: docker
  container_name: mic_cms_ms_api


  